### ISSUE TITLE
Responsive: Sign in and sign up option disappears on small screen and horizontal scroll is there on small screens 

### ISSUE THREAD

**Issue by Garimas10u** [ayush-that/FinVeda#303] opened 2024-06-14 16:02 UTC
no sign in sign up option in mobile view and there is 
![Uploading Screenshot 2024-06-14 211957.png…]()
a horizontal scroll which can be easily fixed

**Comment by Garimas10u** [comment] 2024-06-14 16:05
please assign me this issue as I would want to work on it

**Comment by Garimas10u** [comment] 2024-06-15 18:06
Thank you for assigning me the issue

**Comment by Agarwalvidu** [comment] 2024-07-20 21:07
As no update is shown by the contributor and the issue is already solved I am closing this issue!

**Closed by Agarwalvidu** 2024-07-20 21:07 UTC
Labels: enhancement, gssoc, gssoc24
