### ISSUE TITLE
Title: Make Feedback form attractive and working

### ISSUE THREAD

**Issue by zalabhavy** [ayush-that/FinVeda#757] opened 2024-07-27 18:11 UTC
### Is your feature request related to a problem? Please describe.

I will make attractive and working feedback form in this website.

![image](https://github.com/user-attachments/assets/c4c7d7a8-f0b6-48b3-911c-f87cb2ef401c)

This is not proper !

### Describe the solution you'd like.

NA

### Describe alternatives you've considered.

NA

### Add any other context or screenshots about the feature request here.

NA

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by zalabhavy** [comment] 2024-07-27 18:11
@deepeshmlgupta @Agarwalvidu Please assign me this task !

Thank You !

**Comment by dhananjay6561** [comment] 2024-07-28 19:45
@zalabhavy The issue is solved now. You may close it

**Closed** 2024-07-29 05:19 UTC
Labels: gssoc, gssoc24
